# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param simulator.modelsimInstallPath D:/modelsim/win64
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/project/project_cpu/project_cpu.cache/wt [current_project]
set_property parent.project_path D:/project/project_cpu/project_cpu.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_cache_permissions disable [current_project]
add_files D:/project/project_cpu/project_cpu.srcs/sources_1/ip/ram_code/ordertry.coe
read_verilog -library xil_defaultlib {
  D:/project/project_cpu/project_cpu.srcs/sources_1/new/ALU.v
  D:/project/project_cpu/project_cpu.srcs/sources_1/new/begin.v
  D:/project/project_cpu/project_cpu.srcs/sources_1/new/chchch.v
  D:/project/project_cpu/project_cpu.srcs/sources_1/new/clknew.v
  D:/project/project_cpu/project_cpu.srcs/sources_1/new/control.v
  D:/project/project_cpu/project_cpu.srcs/sources_1/new/dataram_do.v
  D:/project/project_cpu/project_cpu.srcs/sources_1/new/datatwoten.v
  D:/project/project_cpu/project_cpu.srcs/sources_1/new/jd.v
  D:/project/project_cpu/project_cpu.srcs/sources_1/new/jump.v
  D:/project/project_cpu/project_cpu.srcs/sources_1/new/jumpaddr.v
  D:/project/project_cpu/project_cpu.srcs/sources_1/new/kkk.v
  D:/project/project_cpu/project_cpu.srcs/sources_1/new/outt.v
  D:/project/project_cpu/project_cpu.srcs/sources_1/new/pc.v
  D:/project/project_cpu/project_cpu.srcs/sources_1/new/pc_new_old.v
  D:/project/project_cpu/project_cpu.srcs/sources_1/new/pcadd.v
  D:/project/project_cpu/project_cpu.srcs/sources_1/new/regester_file.v
  D:/project/project_cpu/project_cpu.srcs/sources_1/new/timep.v
  D:/project/project_cpu/project_cpu.srcs/sources_1/new/cpu.v
}
read_ip -quiet D:/project/project_cpu/project_cpu.srcs/sources_1/ip/data_ram/data_ram.xci
set_property used_in_implementation false [get_files -all d:/project/project_cpu/project_cpu.srcs/sources_1/ip/data_ram/data_ram_ooc.xdc]

read_ip -quiet D:/project/project_cpu/project_cpu.srcs/sources_1/ip/mult_gen_0/mult_gen_0.xci

read_ip -quiet D:/project/project_cpu/project_cpu.srcs/sources_1/ip/ram_code/ram_code.xci
set_property used_in_implementation false [get_files -all d:/project/project_cpu/project_cpu.srcs/sources_1/ip/ram_code/ram_code_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/project/project_cpu/project_cpu.srcs/constrs_1/new/cpu.xdc
set_property used_in_implementation false [get_files D:/project/project_cpu/project_cpu.srcs/constrs_1/new/cpu.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top cpu -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef cpu.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file cpu_utilization_synth.rpt -pb cpu_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
